services:
  crypto-api:
    build:
      context: .
    container_name: crypto-api
    ports:
      - "8080:80"
    environment:
      CRYPTO_PRICE_API_KEY: "CG-nWzg3BN9TLZdJEs3mNn5eWPA"

  crypto-db:
    image: postgres:14.2
    container_name: crypto-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: crypto-db
