// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/prices": {
            "get": {
                "description": "Returns latest crypto prices for given symbols and currencies.",
                "tags": [
                    "prices"
                ],
                "summary": "Current crypto prices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Crypto symbols (e.g. btc, eth)",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Fiat currencies (default: usd)",
                        "name": "currency",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.GetPricesResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Price": {
            "type": "object",
            "properties": {
                "exchangeRate": {
                    "type": "number",
                    "format": "float64"
                },
                "pair": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "v1.GetPricesResponse": {
            "type": "object",
            "properties": {
                "from_cache": {
                    "type": "boolean"
                },
                "prices": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/models.Price"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Crypto Price API",
	Description:      "API for fetching crypto currency prices.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
